package vault5431.users;

import org.json.JSONException;
import org.json.JSONObject;
import vault5431.crypto.exceptions.InvalidPublicKeySignature;
import vault5431.crypto.sjcl.SJCLAsymmetricField;
import vault5431.io.Base64String;

import java.io.IOException;
import java.util.UUID;

/**
 * Password class. Represents an entry in the password vault.
 *
 * @author papacharlie
 */
public final class SharedPassword {

    private String sharer;
    private SJCLAsymmetricField name;
    private SJCLAsymmetricField url;
    private SJCLAsymmetricField username;
    private SJCLAsymmetricField password;
    private SJCLAsymmetricField notes;
    private Base64String signature;
    private UUID id;

    /**
     * Creates a new SharedPassword instance. This constructor limits the total stored size of the instance. Used when
     * loading instances from disk.
     *
     * @param sharer    user sharing this password
     * @param name      website's name
     * @param url       website's url
     * @param username  website's username
     * @param password  website's password
     * @param signature signature generated by sharer's private key
     * @param id        unique id for indexing server/client side
     *                  @param notes password's notes
     * @throws IllegalArgumentException When any of the fields are empty, or either exceed the max size of 750 characters.
     */
    private SharedPassword(String sharer, String name, String url, String username, String password, String notes, Base64String signature, UUID id) throws IllegalArgumentException {
        try {
            if (UserManager.userExists(sharer)) {
                this.sharer = sharer;
            } else {
                throw new IllegalArgumentException("Sharer does not exist!");
            }
            this.name = new SJCLAsymmetricField(name, 150); // 100 char limit
            this.url = new SJCLAsymmetricField(url, 512);
            this.username = new SJCLAsymmetricField(username, 150);
            this.password = new SJCLAsymmetricField(password, 150);
            this.notes = new SJCLAsymmetricField(notes, 1350); // 1000 char limit
            if (signature.size() == 128) {
                this.signature = signature;
            } else {
                throw new IllegalArgumentException("Signature is invalid!");
            }
            this.id = id;
        } catch (JSONException err) {
            err.printStackTrace();
            throw new IllegalArgumentException("All fields must be valid JSON");
        } catch (NullPointerException err) {
            throw new IllegalArgumentException("All fields required");
        }
    }

    /**
     * Parses a JSON object ideally created by {@link #toJSONObject}, otherwise simply requires all fields be present in the object.
     *
     * @param json JSONObject representing the Password
     * @return Password instance parsed from JSON.
     * @throws IllegalArgumentException Thrown by Password constructor or if JSON object does not contain all required
     *                                  fields.
     */
    public static SharedPassword fromJSON(JSONObject json) throws IllegalArgumentException {
        if (json.has("sharer") && json.has("name") && json.has("url") && json.has("username") && json.has("password") && json.has("notes") && json.has("signature") && json.has("id")) {
            return new SharedPassword(
                    json.get("sharer").toString(),
                    json.get("name").toString(),
                    json.get("url").toString(),
                    json.get("username").toString(),
                    json.get("password").toString(),
                    json.get("notes").toString(),
                    Base64String.fromBase64(json.get("signature").toString()),
                    UUID.fromString(json.getString("id"))
            );
        } else {
            throw new IllegalArgumentException("All fields required");
        }
    }

    public static SharedPassword fromJSON(String json) throws IllegalArgumentException {
        try {
            return fromJSON(new JSONObject(json));
        } catch (JSONException err) {
            throw new IllegalArgumentException("Invalid JSON");
        }
    }

    public static SharedPassword fromJSON(Base64String json) {
        return fromJSON(json.decodeString());
    }

    /**
     * @return The JSON representation of the SharedPassword.
     */
    public JSONObject toJSONObject() {
        JSONObject json = new JSONObject();
        json.put("sharer", sharer);
        json.put("name", name);
        json.put("url", url);
        json.put("username", username);
        json.put("password", password);
        json.put("notes", notes);
        json.put("signature", signature.getB64String());
        json.put("id", id.toString());
        return json;
    }

    public User getSharerUser() {
        return UserManager.getUser(sharer);
    }

    public String getSharer() {
        return sharer;
    }

    public String getSharerPublicSigningKey() throws IOException, InvalidPublicKeySignature {
        return UserManager.getUser(sharer).loadAndVerifyPublicSigningKey();
    }

    public String toJSON() {
        return toJSONObject().toString();
    }

    /**
     * @return The Password's unique ID.
     */
    public UUID getID() {
        return id;
    }

    void newUUID() {
        id = UUID.randomUUID();
    }

    public int hashCode() {
        return id.hashCode();
    }

    public boolean equals(Object obj) {
        if (obj instanceof SharedPassword) {
            SharedPassword other = (SharedPassword) obj;
            return id.equals(other.id);
        } else {
            return false;
        }
    }

}
